### ISSUE TITLE
[Orderbook] Module has confusing file structure

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#839]
There are many files, some of which corresponding to orderbook models and others are helper functions.

1. helpers: util and auction_data_reader. Perhaps auction_data_reader should be part of util?

2. Also, I would propose that the files related to orderbook models all be renamed to begin with orderbook so they are batched together, **or** put into their own directory "orderbook" and be renamed without term orderbook.

3. Then there is this other folder "streamed" which contains yet another orderbook model along with a bunch of scattered files that look like a bunch of new models. I might also propose that we consolidate the models introduced here into a single file models.rs or use the already existing models in the projects model directory.

Of course these are just my first thoughts when looking at this directory. Just a thought

<img width="297" alt="Screenshot 2020-05-04 at 2 12 38 PM" src="https://user-images.githubusercontent.com/11778116/80964812-cc378400-8e11-11ea-812f-a25e50195909.png">

**Comment by nlordell** [comment]
Can you elaborate? I find the module directory to be fairly clean.

**Comment by bh2smith** [comment]
Yes, there are many files. Some of which corresponding to Orderbook Models and others are helper functions. 

1. _helpers:_ `util` and `auction_data_reader`. Perhaps `auction_data_reader` should be part of util? 

2. Also, I would propose that the files related to orderbook models all be renamed to begin with orderbook so they are batched together, or put into their own directory "orderbook" and be renamed without term orderbook.

3. Then there is this other folder "streamed" which contains yet another orderbook model along with a bunch of scattered files that look like a bunch of new models. I might also propose that we consolidate the models introduced here into a single file `models.rs` or use the already existing models in the projects model directory. 

Of course these are just my first thoughts when looking at this directory.

**Comment by nlordell** [comment]
Is this fixed now that all `mod.rs` files have been renamed?

**Comment by bh2smith** [comment]
Ya, I guess so although we still have the term "orderbook" in the filenames while auction_data_reader strikes me as more of a util and I would also expect "updating_orderbook" to be sitting right next to its friends. However, it seems like I am the only one who gets this impression from the orderbook module. If nothing changes by the end of the week, I guess we can close it.

**Comment by nlordell** [comment]
Ah ok, I confused this with another case then - lets leave it open for now.

**Comment by fleupold** [comment]
@bh2smith do you want to make a suggestion on how to rename the modules in a PR or do you think we can close this?

**Comment by bh2smith** [comment]
My suggestion would be to eliminate the streamed directory and move `updating_orderbook` into the main repo while moving other "base" models into a more accessible location (if possible). I would like to either remove the term `orderbook` from the filenames or put it first so that all "orderbook" models be together... 

I feel like I have already made these suggestions. I will try and take a stab at this ASAP.

**Comment by fleupold** [comment]
If you feel the names aren't clear that is perfectly fine and probably a sign that they won't be clear to other people either. I'd just ask you to suggest the changes in form of a PR which will make it easy for us to see and approve them (_code wins arguments_)
